version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: local-postgres
    environment:
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: dongnaebook_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - db-network

volumes:
  postgres_data:

networks:
  db-network:
