package com.dongnaebook.domain.diary;

import com.dongnaebook.domain.album.Album;
import com.dongnaebook.domain.user.User;
import jakarta.persistence.*;
import lombok.Getter;
import lombok.Setter;

import java.time.LocalDateTime;

@Getter
@Setter
@Entity
public class Diary {
    @Id
    @GeneratedValue
    private Long id;

    private String title;
    private String content;

    private String region;
    private String keywords;

    private boolean isAutoGenerated;

    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="user_id")
    private User user;

    @ManyToOne(fetch=FetchType.LAZY)
    private Album album;

    private LocalDateTime createdAt;
    private LocalDateTime updatedAt;
}
