package com.dongnaebook.domain.diary;

import com.dongnaebook.common.domain.BaseEntity;
import com.dongnaebook.domain.post.Post;
import com.dongnaebook.domain.user.User;
import jakarta.persistence.*;
import lombok.*;
import lombok.experimental.SuperBuilder;

import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;

@Getter
@Setter
@Table(name="diaries")
@Entity
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class Diary extends BaseEntity {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column(nullable=false)
    private String title;

    @Column(columnDefinition = "TEXT")
    private String content;

    @Column(columnDefinition = "TEXT")
    private String keywords;

    private boolean isAutoGenerated;

    public void update(String title, String content) {
        this.title = title;
        this.content = content;
    }
}
