package com.dongnaebook.domain.diary;

import com.dongnaebook.common.domain.BaseEntity;
import com.dongnaebook.domain.post.Post;
import com.dongnaebook.domain.user.User;
import jakarta.persistence.*;
import lombok.*;
import lombok.experimental.SuperBuilder;

import java.time.LocalDateTime;

@Getter
@Setter
@Table(name="diaries")
@Entity
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class Diary extends BaseEntity {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column(nullable=false)
    private String title;
    @Lob
    private String content;

    private String region;
    private String keywords;

    @Column(nullable=false)
    private LocalDateTime date;

    private boolean isAutoGenerated;

    public void update(String title, String content) {
        this.title = title;
        this.content = content;
    }


    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="post_id", referencedColumnName="id", nullable=false)
    private Post post;
}
