package com.dongnaebook.domain.diary;

import com.dongnaebook.domain.diary.DTO.DiaryRequest;
import com.dongnaebook.domain.diary.DTO.DiaryResponse;
import lombok.Getter;
import lombok.Setter;

@Getter
@Setter
public class DiaryMapper {
    public static Diary toEntity(DiaryRequest diaryRequest) {
        Diary diary = new Diary();
        diary.setTitle(diaryRequest.getTitle());
        diary.setContent(diaryRequest.getContent());
        diary.setRegion(diaryRequest.getRegion());
        diary.setKeywords(diaryRequest.getKeyword());
        diary.setCreatedAt(diaryRequest.getCreatedAt());
        diary.setUpdatedAt(diaryRequest.getUpdatedAt());
        diary.setAutoGenerated(diaryRequest.isAutoGenerated());
        return diary;
    }

    public static DiaryResponse toResponse(Diary diary) {
        return DiaryResponse.builder()
                .id(diary.getId())
                .title(diary.getTitle())
                .content(diary.getContent())
                .region(diary.getRegion())
                .keyword(diary.getKeywords())
                .createdAt(diary.getCreatedAt())
                .updatedAt(diary.getUpdatedAt())
                .build();

    }
}
