package com.dongnaebook.domain.diary.DTO;

public class DiaryRequest {
    private String title;
    private String content;
    private String region;
    private String keywords;
    private Long albumId;
    private boolean isAutoGenerated;
}
