package com.dongnaebook.domain.diary.DTO;

import lombok.Getter;
import lombok.Setter;

import java.time.LocalDateTime;

@Getter
@Setter
public class DiaryRequest {
    private String title;
    private String content;
    private String region;
    private String keyword;
    private Long albumId;
    private LocalDateTime createdAt;
    private LocalDateTime updatedAt;
    private boolean isAutoGenerated;
}
