package com.dongnaebook.domain.diary.DTO;

import com.dongnaebook.domain.post.DTO.PostResponseDTO;
import com.dongnaebook.domain.region.DTO.RegionResponseDTO;
import com.dongnaebook.domain.user.DTO.UserResponseDTO;
import lombok.*;
import lombok.experimental.SuperBuilder;

import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.List;

@Getter
@Setter
@SuperBuilder
@NoArgsConstructor
@AllArgsConstructor
public class DiaryDetailDTO {
    private Long id;
    private String title;
    private String content;
    private String keywords; // 키워드 목록
    private List<PostResponseDTO> posts;
    private UserResponseDTO createdBy;   // 일기를 작성한 사용자 정보
    private LocalDateTime createdAt;
    private UserResponseDTO modifiedBy; // 일기를 수정한 사용자 정보
    private LocalDateTime modifiedAt;
    private boolean isAutoGenerated; // 자동 생성 여부
    private List<RegionResponseDTO> regions; // 지역 정보

}
