package com.dongnaebook.domain.diary.DTO;

import lombok.Getter;
import lombok.Setter;

import java.time.LocalDate;
import java.util.List;

@Getter
@Setter
public class DiaryRequestDTO {
    private String title;
    private String content;
    private String keywords;
    private boolean isAutoGenerated;
    private List<Long> postIds;
}
