package com.dongnaebook.domain.diary.DTO;

import com.dongnaebook.common.domain.DTO.BaseDTO;
import com.dongnaebook.domain.diary.Diary;
import com.dongnaebook.domain.user.DTO.UserResponseDTO;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.experimental.SuperBuilder;

import java.time.LocalDateTime;
import java.util.List;

@Getter
@SuperBuilder
@AllArgsConstructor
public class DiaryResponseDTO extends BaseDTO {
    private Long id;
    private String title;
    private String content;
    private String keywords;
    private boolean isAutoGenerated;
}
